[modules]
autoload = yes

; 불필요한 모듈 비활성화 (경량화)
noload => chan_skinny.so
noload => chan_mgcp.so
noload => chan_h323.so
noload => chan_ooh323.so
noload => app_voicemail.so
noload => res_phoneprov.so
noload => chan_unistim.so
